language: go
dist: xenial

go:
  - 1.11.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/websocket
  - go get github.com/bclicn/color
  - go get github.com/rs/cors
  - go get github.com/stretchr/testify
  - go get github.com/syndtr/goleveldb/leveldb

script: go test -v -coverprofile cover.out