language: go
os:
  - linux

go:
  - 1.11.x

addons:
  mariadb: '10.0'

services:
  - redis-server
  - mongodb

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/websocket
  - go get github.com/rs/cors
  - go get github.com/syndtr/goleveldb/leveldb
  - go get github.com/benitogf/coat
  - go get github.com/stretchr/testify
  - go get github.com/gobwas/glob
  - go get github.com/go-sql-driver/mysql
  - go get github.com/go-redis/redis
  - go get github.com/benitogf/mongo-go-driver/mongo
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/benitogf/json-patch

before_script:
  - mysql -u root < samo.sql

script:
  - go vet ./...
  - go test -v -coverprofile cover.out -count 1 -failfast -race -bench .