language: go
os:
  - linux

go:
  - 1.12.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/websocket
  - go get github.com/rs/cors
  - go get github.com/syndtr/goleveldb/leveldb
  - go get github.com/benitogf/coat
  - go get github.com/stretchr/testify
  - go get github.com/gobwas/glob
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/benitogf/jsonpatch
  - go get github.com/nsf/jsondiff
  - go get go.etcd.io/etcd/clientv3

before_script:
  - go get -v go.etcd.io/etcd
  - nohup $GOPATH/bin/etcd &

script:
  - go vet ./...
  - go test -v -coverprofile cover.out -count 1 -failfast -race -bench .