language: go
os:
  - linux
  - windows

go:
  - 1.11.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/websocket
  - go get github.com/rs/cors
  - go get github.com/syndtr/goleveldb/leveldb
  - go get github.com/benitogf/coat
  - go get github.com/stretchr/testify
  - go get gopkg.in/godo.v2/glob
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/go-sql-driver/mysql

script:
  - go vet ./...
  - go test -v -coverprofile cover.out -count 1 -failfast -race -bench .